services:
  - type: web
    name: my-portfolio-web
    env: java
    plan: free
    region: singapore 
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/portfolio-0.0.1-SNAPSHOT.jar
    envVars:
      - key: GEMINI_API_KEY
        sync: false 
